import { YearData } from './types';

export const mockYearData: YearData[] = [
  {
    year: 2024,
    showCount: 12,
    artistCount: 8,
    venueCount: 6,
    isTopYear: true,
    logs: [
      {
        id: 1,
        artist: 'Taylor Swift',
        tour: 'The Eras Tour',
        venue: 'SoFi Stadium',
        city: 'Los Angeles, CA',
        date: 'Dec 15, 2024',
        dateObj: new Date('2024-12-15'),
        rating: 5,
        note: 'Cried during All Too Well. Worth it.',
        photos: ['https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800'],
        badges: [
          { id: 1, name: '500 Mile', icon: '🏆' },
          { id: 2, name: '1st TN', icon: '🎭' },
        ],
        friends: [
          { id: 1, name: 'Sarah', avatar: 'https://i.pravatar.cc/150?img=1' },
          { id: 2, name: 'Mike', avatar: 'https://i.pravatar.cc/150?img=2' },
          { id: 3, name: 'Emma', avatar: 'https://i.pravatar.cc/150?img=3' },
        ],
        isFeatured: true,
      },
      {
        id: 2,
        artist: 'Arctic Monkeys',
        venue: 'Madison Square Garden',
        city: 'New York, NY',
        date: 'Nov 28, 2024',
        dateObj: new Date('2024-11-28'),
        rating: 4,
        photos: ['https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=400'],
      },
      {
        id: 3,
        artist: 'The Weeknd',
        venue: 'Barclays Center',
        city: 'Brooklyn, NY',
        date: 'Nov 15, 2024',
        dateObj: new Date('2024-11-15'),
        rating: 5,
        photos: ['https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400'],
      },
      {
        id: 4,
        artist: 'Billie Eilish',
        venue: 'The Forum',
        city: 'Inglewood, CA',
        date: 'Oct 20, 2024',
        dateObj: new Date('2024-10-20'),
        rating: 5,
        note: 'Her voice is even better live!',
        photos: ['https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800'],
        isFeatured: true,
      },
    ],
    milestones: [
      {
        id: 1,
        type: 'shows',
        icon: '🎉',
        message: '10 shows in 2024',
        insertAfterLogId: 3,
      },
    ],
  },
  {
    year: 2023,
    showCount: 8,
    artistCount: 6,
    venueCount: 5,
    logs: [
      {
        id: 5,
        artist: 'Bad Bunny',
        venue: 'SoFi Stadium',
        city: 'Los Angeles, CA',
        date: 'Aug 12, 2023',
        dateObj: new Date('2023-08-12'),
        rating: 5,
        photos: ['https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400'],
      },
    ],
  },
];
